import type { Metadata } from "next";
import { Inter_Tight as Inter } from "next/font/google";
import "./globals.css";
import { Providers as ThemeProvider } from "@/components/theme-provider"
import NavbarDesktop from '../components/NavbarDesktop';
import Footer from '../components/Footer';
import NavbarMobile from '../components/NavbarMobile';

const inter = Inter({ subsets: ["latin"], display: "block" });

export const metadata: Metadata = {
  title: "Adi Muhamad Firmansyah | Fullstack Developer",
  description: "Generated by create next app",
  openGraph: {
    title: 'Adi Muhamad Firmansyah | Fullstack Developer',
    description: 'Adi Muhamad Firmansyah, A full-stack developer focused on building scalable back-end solutions and crafting seamless user experiences. Over 1 year of experience in full-stack development using Node.js.',
    url: 'https://adimf.dev',
    siteName: 'Adi Muhamad Firmansyah',
    images: [
      {
        url: 'https://adimf.vercel.app/image-open-graph.png',
        width: 800,
        height: 600,
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider >
          <header>
            <NavbarDesktop />
            <NavbarMobile />
          </header>
          <main className="flex flex-col items-center justify-between p-8 gap-8 max-w-7xl mx-auto">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
